spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/inventory_db

  kafka:
    bootstrap-servers: kafka:9092

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/distributed-app

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

server:
  port: 8082
