spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/inventory_db

  kafka:
    bootstrap-servers: localhost:9092

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/distributed-app

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082
